# In Class Exercise 7 - Last one!

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import confusion_matrix, classification_report
from scipy import stats
from sklearn import metrics

In [12]:
# Load mortgage data
mortgage = pd.read_csv("mortgage.txt", sep="|", na_values=["NA", "-", ""])

#Drop na values:
mortgage.dropna(inplace=True)

display(mortgage)
dummies = pd.get_dummies(mortgage["Year"])


# Concatenate the original DataFrame with the new dummy DataFrame
mortgage = pd.concat([mortgage, dummies], axis=1)
mortgage.drop("Year", axis=1, inplace=True)
display(mortgage)
type(dummies)

      CreditScore  HomeAge  YearsEmployed  CreditCardDebt    Year  Default
0             752       24            3.0          8930.0  2009.0        1
1             715        9            8.0          6403.0  2009.0        0
2             635       16            5.0          7561.0  2008.0        0
3             744       20            6.0          8628.0  2008.0        1
4             756       26            8.0          6083.0  2008.0        0
...           ...      ...            ...             ...     ...      ...
1290          786       21            3.0          5544.0  2007.0        0
1291          720       20            6.0          9676.0  2009.0        1
1292          676       17            4.0          8555.0  2008.0        1
1293          620       12            5.0          5370.0  2007.0        0
1294          769       11            3.0          7047.0  2009.0        0

[1290 rows x 6 columns]

,CreditScore,HomeAge,YearsEmployed,CreditCardDebt,Default,2007.0,2008.0,2009.0
0,752,24,3.0,8930.0,1,False,False,True
1,715,9,8.0,6403.0,0,False,False,True
2,635,16,5.0,7561.0,0,False,True,False
3,744,20,6.0,8628.0,1,False,True,False
4,756,26,8.0,6083.0,0,False,True,False
...,...,...,...,...,...,...,...,...
1290,786,21,3.0,5544.0,0,True,False,False
1291,720,20,6.0,9676.0,1,False,False,True
1292,676,17,4.0,8555.0,1,False,True,False
1293,620,12,5.0,5370.0,0,True,False,False
1294,769,11,3.0,7047.0,0,False,False,True

pandas.DataFrame

In [7]:
X = mortgage.drop("Default", axis=1).values
y = mortgage["Default"].values
X

array([[752, 24, 3.0, ..., False, False, True],
       [715, 9, 8.0, ..., False, False, True],
       [635, 16, 5.0, ..., False, True, False],
       ...,
       [676, 17, 4.0, ..., False, True, False],
       [620, 12, 5.0, ..., True, False, False],
       [769, 11, 3.0, ..., False, False, True]],
      shape=(1290, 7), dtype=object)

In [8]:
X = mortgage.drop("Default", axis=1).values
y = mortgage["Default"].values

# Split into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0) #80% is training data, 20% is testing data
log = LogisticRegression(max_iter=1000)

# Fit the classifier to the training data
log.fit(X_train, y_train)

y_pred = log.predict(X_test)

# Print the accuracy
print(log.score(X_test, y_test))

print(classification_report(y_test, y_pred))

0.9108527131782945
              precision    recall  f1-score   support

           0       0.94      0.94      0.94       200
           1       0.80      0.81      0.80        58

    accuracy                           0.91       258
   macro avg       0.87      0.88      0.87       258
weighted avg       0.91      0.91      0.91       258

# Let's try the same thing with a Decision Tree classifier

In [10]:
X = mortgage.drop("Default", axis=1).values
y = mortgage["Default"].values

# Split into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0) #80% is training data, 20% is testing data
tree = DecisionTreeClassifier(random_state=0)

# Fit the classifier to the training data
tree.fit(X_train, y_train)

y_pred = tree.predict(X_test)

# Print the accuracy
print(tree.score(X_test, y_test))

print(classification_report(y_test, y_pred))

0.8294573643410853
              precision    recall  f1-score   support

           0       0.90      0.88      0.89       200
           1       0.61      0.67      0.64        58

    accuracy                           0.83       258
   macro avg       0.76      0.77      0.76       258
weighted avg       0.84      0.83      0.83       258

# Let's try the same thing with a KNN classifier

In [13]:
knn = KNeighborsClassifier(n_neighbors=7)

# Fit the classifier to the training data
knn.fit(X_train, y_train)

y_pred = knn.predict(X_test)

# Print the accuracy
print(knn.score(X_test, y_test))

print(classification_report(y_test, y_pred))

0.9031007751937985
              precision    recall  f1-score   support

           0       0.95      0.93      0.94       200
           1       0.76      0.83      0.79        58

    accuracy                           0.90       258
   macro avg       0.86      0.88      0.87       258
weighted avg       0.91      0.90      0.90       258

# Which one has the highest accuracy? Type below:

logistic regression

In [14]:
#Create a blank dictionary called summary
summary = {}

In [15]:
from sklearn.model_selection import GridSearchCV
mod = GridSearchCV(
    estimator=MLPClassifier(hidden_layer_sizes=(4,), activation="tanh", max_iter=500, random_state=0), 
    param_grid={
        'hidden_layer_sizes': [(5,), (10,)],
        'max_iter': [200, 500, 1000],
        'activation': ["tanh", "relu"]
        
        },
        scoring='roc_auc',
    cv=5)

In [16]:
mod.fit(X,y)
results = pd.DataFrame(mod.cv_results_)
display(results)

/home/jrgoebel/.local/lib/python3.11/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/jrgoebel/.local/lib/python3.11/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_activation,param_hidden_layer_sizes,param_max_iter,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.149290,0.008077,0.001644,0.000189,tanh,"(5,)",200,"{'activation': 'tanh', 'hidden_layer_sizes': (...",0.492424,0.492462,0.500000,0.500000,0.500000,0.496977,0.003702,10
1,0.144489,0.002603,0.001490,0.000034,tanh,"(5,)",500,"{'activation': 'tanh', 'hidden_layer_sizes': (...",0.492424,0.492462,0.500000,0.500000,0.500000,0.496977,0.003702,10
2,0.145718,0.002295,0.001546,0.000100,tanh,"(5,)",1000,"{'activation': 'tanh', 'hidden_layer_sizes': (...",0.492424,0.492462,0.500000,0.500000,0.500000,0.496977,0.003702,10
3,0.163584,0.045770,0.001587,0.000060,tanh,"(10,)",200,"{'activation': 'tanh', 'hidden_layer_sizes': (...",0.959217,0.931863,0.942211,0.942722,0.932714,0.941745,0.009856,7
4,0.164591,0.045863,0.001617,0.000087,tanh,"(10,)",500,"{'activation': 'tanh', 'hidden_layer_sizes': (...",0.959217,0.931863,0.942211,0.942722,0.932714,0.941745,0.009856,7
5,0.164040,0.045549,0.001538,0.000029,tanh,"(10,)",1000,"{'activation': 'tanh', 'hidden_layer_sizes': (...",0.959217,0.931863,0.942211,0.942722,0.932714,0.941745,0.009856,7
6,0.102928,0.023551,0.001527,0.000060,relu,"(5,)",200,"{'activation': 'relu', 'hidden_layer_sizes': (...",0.968771,0.945831,0.938251,0.937910,0.918150,0.941782,0.016314,4
7,0.102993,0.023048,0.001495,0.000043,relu,"(5,)",500,"{'activation': 'relu', 'hidden_layer_sizes': (...",0.968771,0.945831,0.938251,0.937910,0.918150,0.941782,0.016314,4
8,0.103047,0.023254,0.001535,0.000057,relu,"(5,)",1000,"{'activation': 'relu', 'hidden_layer_sizes': (...",0.968771,0.945831,0.938251,0.937910,0.918150,0.941782,0.016314,4
9,0.212115,0.076427,0.001597,0.000101,relu,"(10,)",200,"{'activation': 'relu', 'hidden_layer_sizes': (...",0.967593,0.922920,0.943616,0.940635,0.956137,0.946180,0.015073,3
10,0.209397,0.076358,0.001508,0.000035,relu,"(10,)",500,"{'activation': 'relu', 'hidden_layer_sizes': (...",0.973485,0.922920,0.943616,0.940635,0.956988,0.947529,0.016921,1
11,0.209873,0.076375,0.001520,0.000053,relu,"(10,)",1000,"{'activation': 'relu', 'hidden_layer_sizes': (...",0.973485,0.922920,0.943616,0.940635,0.956988,0.947529,0.016921,1

# Perform a grid search comparison of MLPClassifier (Neural Network), KNN, and Decision Tree. Determine the best parameters for each and the highest roc_auc score.

## Save the result as a tuple (roc_auc_score, parameters) in the summary dictionary. In the end, print out the summary dictionary to show the best classifier with the best hyperparameters.

##### For knn use this for the parameter grid:

'n_neighbors': [1,3,5,7],
'metric': ["euclidean","manhattan"]

In [19]:
from sklearn.model_selection import GridSearchCV
mod = GridSearchCV(
    estimator=KNeighborsClassifier(n_neighbors=3),
    param_grid={
        'n_neighbors' : [1,3,5,7],
        'metric' : ["euclidean", "manhattan"]
        },
        scoring='roc_auc',
    cv=5)

In [20]:
mod.fit(X,y)
results = pd.DataFrame(mod.cv_results_)
display(results)

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_metric,param_n_neighbors,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.001341,0.000191,0.002157,0.000090,euclidean,1,"{'metric': 'euclidean', 'n_neighbors': 1}",0.840404,0.780257,0.781833,0.792820,0.821054,0.803274,0.023637,8
1,0.001205,0.000010,0.002126,0.000012,euclidean,3,"{'metric': 'euclidean', 'n_neighbors': 3}",0.942382,0.904608,0.900477,0.880504,0.908696,0.907333,0.020023,6
2,0.001198,0.000018,0.002169,0.000016,euclidean,5,"{'metric': 'euclidean', 'n_neighbors': 5}",0.963931,0.919513,0.923771,0.890512,0.909463,0.921438,0.024144,3
3,0.001210,0.000009,0.002231,0.000006,euclidean,7,"{'metric': 'euclidean', 'n_neighbors': 7}",0.966330,0.921812,0.937867,0.916149,0.906950,0.929822,0.020841,1
4,0.001205,0.000017,0.002052,0.000012,manhattan,1,"{'metric': 'manhattan', 'n_neighbors': 1}",0.862879,0.807257,0.790307,0.792820,0.832042,0.817061,0.027288,7
5,0.001203,0.000012,0.002154,0.000013,manhattan,3,"{'metric': 'manhattan', 'n_neighbors': 3}",0.953451,0.911294,0.912060,0.870326,0.905034,0.910433,0.026426,5
6,0.001191,0.000016,0.002230,0.000054,manhattan,5,"{'metric': 'manhattan', 'n_neighbors': 5}",0.962290,0.910527,0.922366,0.894515,0.911549,0.920249,0.022822,4
7,0.001203,0.000010,0.002247,0.000009,manhattan,7,"{'metric': 'manhattan', 'n_neighbors': 7}",0.966961,0.922877,0.932544,0.917213,0.906993,0.929318,0.020561,2

### For the decision tree use these for the parameter grid:
    'max_depth': [10, 20, 30, None],
    'min_samples_split': [2, 5, 10]

In [21]:
from sklearn.model_selection import GridSearchCV
mod = GridSearchCV(
    estimator=DecisionTreeClassifier(random_state=0),
    param_grid={
        'max_depth': [10, 20, 30, None],
        'min_samples_split': [2, 5, 10]
        },
        scoring='roc_auc',
    cv=5)

In [22]:
mod.fit(X,y)
results = pd.DataFrame(mod.cv_results_)
display(results)

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_max_depth,param_min_samples_split,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.003560,0.001119,0.001855,0.000561,10,2,"{'max_depth': 10, 'min_samples_split': 2}",0.829798,0.800187,0.798228,0.857508,0.837109,0.824566,0.022618,9
1,0.004866,0.001368,0.002891,0.000726,10,5,"{'max_depth': 10, 'min_samples_split': 5}",0.866961,0.851588,0.811856,0.860702,0.854229,0.849067,0.019356,5
2,0.002665,0.000198,0.001441,0.000012,10,10,"{'max_depth': 10, 'min_samples_split': 10}",0.911953,0.889873,0.857721,0.890043,0.871093,0.884137,0.018490,4
3,0.002704,0.000063,0.001400,0.000008,20,2,"{'max_depth': 20, 'min_samples_split': 2}",0.832071,0.793757,0.805042,0.783409,0.820118,0.806879,0.017529,10
4,0.002639,0.000061,0.001430,0.000011,20,5,"{'max_depth': 20, 'min_samples_split': 5}",0.862795,0.830466,0.807086,0.820586,0.839153,0.832017,0.018723,6
5,0.002584,0.000073,0.001427,0.000003,20,10,"{'max_depth': 20, 'min_samples_split': 10}",0.909764,0.889873,0.858147,0.890043,0.873009,0.884167,0.017458,1
6,0.002676,0.000082,0.001399,0.000003,30,2,"{'max_depth': 30, 'min_samples_split': 2}",0.832071,0.793757,0.805042,0.783409,0.820118,0.806879,0.017529,10
7,0.002655,0.000086,0.001399,0.000009,30,5,"{'max_depth': 30, 'min_samples_split': 5}",0.862795,0.830466,0.807086,0.820586,0.839153,0.832017,0.018723,6
8,0.002629,0.000091,0.001539,0.000237,30,10,"{'max_depth': 30, 'min_samples_split': 10}",0.909764,0.889873,0.858147,0.890043,0.873009,0.884167,0.017458,1
9,0.002714,0.000131,0.001412,0.000011,None,2,"{'max_depth': None, 'min_samples_split': 2}",0.832071,0.793757,0.805042,0.783409,0.820118,0.806879,0.017529,10
10,0.002649,0.000059,0.001450,0.000011,None,5,"{'max_depth': None, 'min_samples_split': 5}",0.862795,0.830466,0.807086,0.820586,0.839153,0.832017,0.018723,6
11,0.002591,0.000065,0.001424,0.000030,None,10,"{'max_depth': None, 'min_samples_split': 10}",0.909764,0.889873,0.858147,0.890043,0.873009,0.884167,0.017458,1