# Data Programming in Python | BAIS:6040
# Notebook Demonstration 4.7 - Reading & Writing a CSV or Excel File Using Pandas

## Reading and Writing a CSV File Using Pandas

In [1]:
import pandas as pd

C:\Users\redmo\AppData\Roaming\Python\Python311\site-packages\pandas\core\arrays\masked.py:61: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (

In [2]:
df = pd.read_csv("outcome/my_titanic.csv")
df

     index  survived  pclass     fare
0        0         0       3   7.2500
1        1         1       1  71.2833
2        2         1       3   7.9250
3        3         1       1  53.1000
4        4         0       3   8.0500
..     ...       ...     ...      ...
886    886         0       2  13.0000
887    887         1       1  30.0000
888    888         0       3  23.4500
889    889         1       1  30.0000
890    890         0       3   7.7500

[891 rows x 4 columns]

pandas.read_csv: https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_csv.html

When you need to read a CSV file and analyze the content in a tabular format with rows and columns, it is a good idea to read the file into a Pandas dataframe.

In [3]:
df = pd.read_csv("outcome/my_titanic.csv", sep="\t")
df

    index,survived,pclass,fare
0                   0,0,3,7.25
1                1,1,1,71.2833
2                  2,1,3,7.925
3                   3,1,1,53.1
4                   4,0,3,8.05
..                         ...
886               886,0,2,13.0
887               887,1,1,30.0
888              888,0,3,23.45
889               889,1,1,30.0
890               890,0,3,7.75

[891 rows x 1 columns]

In [4]:
df = pd.read_csv("https://people.sc.fsu.edu/~jburkardt/data/csv/biostats.csv")
df

    Name       "Sex"   "Age"   "Height (in)"   "Weight (lbs)"
0   Alex         "M"      41              74              170
1   Bert         "M"      42              68              166
2   Carl         "M"      32              70              155
3   Dave         "M"      39              72              167
4   Elly         "F"      30              66              124
5   Fran         "F"      33              66              115
6   Gwen         "F"      26              64              121
7   Hank         "M"      30              71              158
8   Ivan         "M"      53              72              175
9   Jake         "M"      32              69              143
10  Kate         "F"      47              69              139
11  Luke         "M"      34              72              163
12  Myra         "F"      23              62               98
13  Neil         "M"      36              75              160
14  Omar         "M"      38              70              145
15  Page         "F"      31              67              135
16  Quin         "M"      29              71              176
17  Ruth         "F"      28              65              131

## Reading Excel Tables with pandas

In [5]:
#! pip install --user openpyxl xlrd xlwt xlsxwriter

If you need to read Excel spreadsheet into a Python program, you can use the pandas `read_excel()` function, which is similar to the `read_csv()` except instead of providing the name of a text file, we provide the name of an Excel file(.xls or .xlsx).

In [6]:
df = pd.read_excel("example_spreadsheet.xlsx", sheet_name="Sheet2")

In [7]:
df

   sale_id  customer_id  product_id  count  unit_price
0     1101          253      700931     35         246
1     1242          256      672523     42         215
2     3901          235      745392     36          73
3     4820          532      853830     15          25
4     2750          146      713548      9         642
5     1101          253      700931     35         246
6     1242          256      672523     42         215
7     3901          235      745392     36          73
8     4820          532      853830     15          25
9     2750          146      713548      9         642

pandas.read_excel: https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_excel.html

## Write pandas DataFrame to CSV File and Excel

In [8]:
df.to_csv("outcome/my_data.csv", sep=",", index=False)

pandas.DataFrame.to_csv: https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.to_csv.html

In [9]:
df.to_excel("outcome/my_data.xlsx", sheet_name="SALES1", index=False)

pandas.DataFrame.to_excel: https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.to_excel.html